import { Inter } from 'next/font/google';
import '../styles/globals.css';
import '@mantine/core/styles.css';
import WrapperProvider from '@/wrapper/wrapperProvider';
import StyledComponentsRegistry from '@/lib/registry';
import { ColorSchemeScript } from '@mantine/core';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <head>
        <ColorSchemeScript />
        <link rel='preconnect' href='https://fonts.googleapis.com' />
        <link
          rel='preconnect'
          href='https://fonts.gstatic.com'
          crossOrigin='anonymous'
        />
        <link
          href='https://fonts.googleapis.com/css2?family=Share+Tech+Mono&display=swap'
          rel='stylesheet'
        />
      </head>
      <body className='font-stmono'>
        <WrapperProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </WrapperProvider>
      </body>
    </html>
  );
}
